# Generated by Django 5.1.1 on 2024-09-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
