# Generated by Django 5.1.1 on 2024-09-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('cridet_hour', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course_title', models.CharField(max_length=200)),
            ],
        ),
    ]
